version: '3.8'

services:
  my_irc_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_irc_server
    ports:
      - "3001:3001"
    networks:
      - my_network
    container_name: ircserver
    restart: unless-stopped
    # Add any additional configuration as needed
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    restart: always
    networks:
      - my_network
    volumes:
      - ~/.thelounge:/var/opt/thelounge # bind lounge config from the host's file system

networks:
  my_network:
    driver: bridge
